chiInfo = {
	'ARG': [("N", "CA", "CB", "CG"),
		("CA", "CB", "CG", "CD"),
		("CB", "CG", "CD", "NE"),
		("CG", "CD", "NE", "CZ")],
	'LYS': [("N", "CA", "CB", "CG"),
		("CA", "CB", "CG", "CD"),
		("CB", "CG", "CD", "CE"),
		("CG", "CD", "CE", "NZ")],
	'MET': [("N", "CA", "CB", "CG"),
		("CA", "CB", "CG", "SD"),
		("CB", "CG", "SD", "CE")],
	'GLU': [("N", "CA", "CB", "CG"),
		("CA", "CB", "CG", "CD"),
		("CB", "CG", "CD", "OE1")],
	'GLN': [("N", "CA", "CB", "CG"),
		("CA", "CB", "CG", "CD"),
		("CB", "CG", "CD", "OE1")],
	'ASP': [("N", "CA", "CB", "CG"),
		("CA", "CB", "CG", "OD1")],
	'ASN': [("N", "CA", "CB", "CG"),
		("CA", "CB", "CG", "OD1")],
	'ILE': [("N", "CA", "CB", "CG1"),
		("CA", "CB", "CG1", "CD1")],
	'LEU': [("N", "CA", "CB", "CG"),
		("CA", "CB", "CG", "CD1")],
	'HIS': [("N", "CA", "CB", "CG"),
		("CA", "CB", "CG", "ND1")],
	'TRP': [("N", "CA", "CB", "CG"),
		("CA", "CB", "CG", "CD1")],
	'TYR': [("N", "CA", "CB", "CG"),
		("CA", "CB", "CG", "CD1")],
	'PHE': [("N", "CA", "CB", "CG"),
		("CA", "CB", "CG", "CD1")],
	'PRO': [("N", "CA", "CB", "CG"),
		("CA", "CB", "CG", "CD")],
	'THR': [("N", "CA", "CB", "OG1")],
	'VAL': [("N", "CA", "CB", "CG1")],
	'SER': [("N", "CA", "CB", "OG")],
	'CYS': [("N", "CA", "CB", "SG")],
}
