##################################################
# file: PdbWebServiceService_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /home/chimera/chimeraBuild_OSMESA/build/build/bin/wsdl2py pdbws.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from PdbWebServiceService_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
class getAnnotationsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getAnnotationsRequest.typecode = Struct(pname=("webservices.pdb.org","getAnnotations"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getAnnotationsRequest, encoded="webservices.pdb.org")

class getAnnotationsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getAnnotationsReturn -- part getAnnotationsReturn
        """
        self._getAnnotationsReturn =  kw.get("getAnnotationsReturn")
getAnnotationsResponse.typecode = Struct(pname=("webservices.pdb.org","getAnnotationsResponse"), ofwhat=[ZSI.TC.String(pname="getAnnotationsReturn", aname="_getAnnotationsReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getAnnotationsResponse, encoded="webservices.pdb.org")

class getEntitiesRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getEntitiesRequest.typecode = Struct(pname=("webservices.pdb.org","getEntities"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getEntitiesRequest, encoded="webservices.pdb.org")

class getEntitiesResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getEntitiesReturn -- part getEntitiesReturn
        """
        self._getEntitiesReturn =  kw.get("getEntitiesReturn")
getEntitiesResponse.typecode = Struct(pname=("webservices.pdb.org","getEntitiesResponse"), ofwhat=[ns0.ArrayOf_xsd_int_Def(pname="getEntitiesReturn", aname="_getEntitiesReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getEntitiesResponse, encoded="webservices.pdb.org")

class blastPDBRequest1:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        in2 -- part in2
        in3 -- part in3
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
        self._in2 =  kw.get("in2")
        self._in3 =  kw.get("in3")
blastPDBRequest1.typecode = Struct(pname=("webservices.pdb.org","blastPDB"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.FPdouble(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in2", aname="_in2", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in3", aname="_in3", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=blastPDBRequest1, encoded="webservices.pdb.org")

class blastPDBResponse1:
    def __init__(self, **kw):
        """Keyword parameters:
        blastPDBReturn -- part blastPDBReturn
        """
        self._blastPDBReturn =  kw.get("blastPDBReturn")
blastPDBResponse1.typecode = Struct(pname=("webservices.pdb.org","blastPDBResponse"), ofwhat=[ZSI.TC.String(pname="blastPDBReturn", aname="_blastPDBReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=blastPDBResponse1, encoded="webservices.pdb.org")

class blastPDBRequest1:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        in2 -- part in2
        in3 -- part in3
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
        self._in2 =  kw.get("in2")
        self._in3 =  kw.get("in3")
blastPDBRequest1.typecode = Struct(pname=("webservices.pdb.org","blastPDB"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.FPdouble(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in2", aname="_in2", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in3", aname="_in3", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=blastPDBRequest1, encoded="webservices.pdb.org")

class blastPDBResponse1:
    def __init__(self, **kw):
        """Keyword parameters:
        blastPDBReturn -- part blastPDBReturn
        """
        self._blastPDBReturn =  kw.get("blastPDBReturn")
blastPDBResponse1.typecode = Struct(pname=("webservices.pdb.org","blastPDBResponse"), ofwhat=[ZSI.TC.String(pname="blastPDBReturn", aname="_blastPDBReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=blastPDBResponse1, encoded="webservices.pdb.org")

class getIdStatusRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getIdStatusRequest.typecode = Struct(pname=("webservices.pdb.org","getIdStatus"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getIdStatusRequest, encoded="webservices.pdb.org")

class getIdStatusResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getIdStatusReturn -- part getIdStatusReturn
        """
        self._getIdStatusReturn =  kw.get("getIdStatusReturn")
getIdStatusResponse.typecode = Struct(pname=("webservices.pdb.org","getIdStatusResponse"), ofwhat=[ZSI.TC.String(pname="getIdStatusReturn", aname="_getIdStatusReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getIdStatusResponse, encoded="webservices.pdb.org")

class getAtomSiteRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getAtomSiteRequest.typecode = Struct(pname=("webservices.pdb.org","getAtomSite"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getAtomSiteRequest, encoded="webservices.pdb.org")

class getAtomSiteResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getAtomSiteReturn -- part getAtomSiteReturn
        """
        self._getAtomSiteReturn =  kw.get("getAtomSiteReturn")
getAtomSiteResponse.typecode = Struct(pname=("webservices.pdb.org","getAtomSiteResponse"), ofwhat=[ns0.Atom_siteWS_Def(pname="getAtomSiteReturn", aname="_getAtomSiteReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getAtomSiteResponse, encoded="webservices.pdb.org")

class getAtomSitesRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getAtomSitesRequest.typecode = Struct(pname=("webservices.pdb.org","getAtomSites"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getAtomSitesRequest, encoded="webservices.pdb.org")

class getAtomSitesResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getAtomSitesReturn -- part getAtomSitesReturn
        """
        self._getAtomSitesReturn =  kw.get("getAtomSitesReturn")
getAtomSitesResponse.typecode = Struct(pname=("webservices.pdb.org","getAtomSitesResponse"), ofwhat=[ns0.ArrayOfAtom_siteWS_Def(pname="getAtomSitesReturn", aname="_getAtomSitesReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getAtomSitesResponse, encoded="webservices.pdb.org")

class getFirstStructSheetRangeRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getFirstStructSheetRangeRequest.typecode = Struct(pname=("webservices.pdb.org","getFirstStructSheetRange"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getFirstStructSheetRangeRequest, encoded="webservices.pdb.org")

class getFirstStructSheetRangeResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getFirstStructSheetRangeReturn -- part getFirstStructSheetRangeReturn
        """
        self._getFirstStructSheetRangeReturn =  kw.get("getFirstStructSheetRangeReturn")
getFirstStructSheetRangeResponse.typecode = Struct(pname=("webservices.pdb.org","getFirstStructSheetRangeResponse"), ofwhat=[ns0.Struct_sheet_rangeWS_Def(pname="getFirstStructSheetRangeReturn", aname="_getFirstStructSheetRangeReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getFirstStructSheetRangeResponse, encoded="webservices.pdb.org")

class getStructSheetRangesRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getStructSheetRangesRequest.typecode = Struct(pname=("webservices.pdb.org","getStructSheetRanges"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getStructSheetRangesRequest, encoded="webservices.pdb.org")

class getStructSheetRangesResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getStructSheetRangesReturn -- part getStructSheetRangesReturn
        """
        self._getStructSheetRangesReturn =  kw.get("getStructSheetRangesReturn")
getStructSheetRangesResponse.typecode = Struct(pname=("webservices.pdb.org","getStructSheetRangesResponse"), ofwhat=[ns0.ArrayOfStruct_sheet_rangeWS_Def(pname="getStructSheetRangesReturn", aname="_getStructSheetRangesReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getStructSheetRangesResponse, encoded="webservices.pdb.org")

class getFirstStructConfRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getFirstStructConfRequest.typecode = Struct(pname=("webservices.pdb.org","getFirstStructConf"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getFirstStructConfRequest, encoded="webservices.pdb.org")

class getFirstStructConfResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getFirstStructConfReturn -- part getFirstStructConfReturn
        """
        self._getFirstStructConfReturn =  kw.get("getFirstStructConfReturn")
getFirstStructConfResponse.typecode = Struct(pname=("webservices.pdb.org","getFirstStructConfResponse"), ofwhat=[ns0.Struct_confWS_Def(pname="getFirstStructConfReturn", aname="_getFirstStructConfReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getFirstStructConfResponse, encoded="webservices.pdb.org")

class getStructConfsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getStructConfsRequest.typecode = Struct(pname=("webservices.pdb.org","getStructConfs"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getStructConfsRequest, encoded="webservices.pdb.org")

class getStructConfsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getStructConfsReturn -- part getStructConfsReturn
        """
        self._getStructConfsReturn =  kw.get("getStructConfsReturn")
getStructConfsResponse.typecode = Struct(pname=("webservices.pdb.org","getStructConfsResponse"), ofwhat=[ns0.ArrayOfStruct_confWS_Def(pname="getStructConfsReturn", aname="_getStructConfsReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getStructConfsResponse, encoded="webservices.pdb.org")

class fastaStructureIdQueryRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        in2 -- part in2
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
        self._in2 =  kw.get("in2")
fastaStructureIdQueryRequest.typecode = Struct(pname=("webservices.pdb.org","fastaStructureIdQuery"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.FPdouble(pname="in2", aname="_in2", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=fastaStructureIdQueryRequest, encoded="webservices.pdb.org")

class fastaStructureIdQueryResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        fastaStructureIdQueryReturn -- part fastaStructureIdQueryReturn
        """
        self._fastaStructureIdQueryReturn =  kw.get("fastaStructureIdQueryReturn")
fastaStructureIdQueryResponse.typecode = Struct(pname=("webservices.pdb.org","fastaStructureIdQueryResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="fastaStructureIdQueryReturn", aname="_fastaStructureIdQueryReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=fastaStructureIdQueryResponse, encoded="webservices.pdb.org")

class fastaQueryRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
fastaQueryRequest.typecode = Struct(pname=("webservices.pdb.org","fastaQuery"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.FPdouble(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=fastaQueryRequest, encoded="webservices.pdb.org")

class fastaQueryResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        fastaQueryReturn -- part fastaQueryReturn
        """
        self._fastaQueryReturn =  kw.get("fastaQueryReturn")
fastaQueryResponse.typecode = Struct(pname=("webservices.pdb.org","fastaQueryResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="fastaQueryReturn", aname="_fastaQueryReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=fastaQueryResponse, encoded="webservices.pdb.org")

class homologyReductionQueryRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
homologyReductionQueryRequest.typecode = Struct(pname=("webservices.pdb.org","homologyReductionQuery"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=homologyReductionQueryRequest, encoded="webservices.pdb.org")

class homologyReductionQueryResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        homologyReductionQueryReturn -- part homologyReductionQueryReturn
        """
        self._homologyReductionQueryReturn =  kw.get("homologyReductionQueryReturn")
homologyReductionQueryResponse.typecode = Struct(pname=("webservices.pdb.org","homologyReductionQueryResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="homologyReductionQueryReturn", aname="_homologyReductionQueryReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=homologyReductionQueryResponse, encoded="webservices.pdb.org")

class keywordQueryRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        in2 -- part in2
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
        self._in2 =  kw.get("in2")
keywordQueryRequest.typecode = Struct(pname=("webservices.pdb.org","keywordQuery"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.Boolean(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.Boolean(pname="in2", aname="_in2", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=keywordQueryRequest, encoded="webservices.pdb.org")

class keywordQueryResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        keywordQueryReturn -- part keywordQueryReturn
        """
        self._keywordQueryReturn =  kw.get("keywordQueryReturn")
keywordQueryResponse.typecode = Struct(pname=("webservices.pdb.org","keywordQueryResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="keywordQueryReturn", aname="_keywordQueryReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=keywordQueryResponse, encoded="webservices.pdb.org")

class pubmedAbstractQueryRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
pubmedAbstractQueryRequest.typecode = Struct(pname=("webservices.pdb.org","pubmedAbstractQuery"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=pubmedAbstractQueryRequest, encoded="webservices.pdb.org")

class pubmedAbstractQueryResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        pubmedAbstractQueryReturn -- part pubmedAbstractQueryReturn
        """
        self._pubmedAbstractQueryReturn =  kw.get("pubmedAbstractQueryReturn")
pubmedAbstractQueryResponse.typecode = Struct(pname=("webservices.pdb.org","pubmedAbstractQueryResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="pubmedAbstractQueryReturn", aname="_pubmedAbstractQueryReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=pubmedAbstractQueryResponse, encoded="webservices.pdb.org")

class getSpaceGroupForStructureRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getSpaceGroupForStructureRequest.typecode = Struct(pname=("webservices.pdb.org","getSpaceGroupForStructure"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getSpaceGroupForStructureRequest, encoded="webservices.pdb.org")

class getSpaceGroupForStructureResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getSpaceGroupForStructureReturn -- part getSpaceGroupForStructureReturn
        """
        self._getSpaceGroupForStructureReturn =  kw.get("getSpaceGroupForStructureReturn")
getSpaceGroupForStructureResponse.typecode = Struct(pname=("webservices.pdb.org","getSpaceGroupForStructureResponse"), ofwhat=[ZSI.TC.String(pname="getSpaceGroupForStructureReturn", aname="_getSpaceGroupForStructureReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getSpaceGroupForStructureResponse, encoded="webservices.pdb.org")

class getPubmedIdForAllStructuresRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        """
getPubmedIdForAllStructuresRequest.typecode = Struct(pname=("webservices.pdb.org","getPubmedIdForAllStructures"), ofwhat=[], pyclass=getPubmedIdForAllStructuresRequest, encoded="webservices.pdb.org")

class getPubmedIdForAllStructuresResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getPubmedIdForAllStructuresReturn -- part getPubmedIdForAllStructuresReturn
        """
        self._getPubmedIdForAllStructuresReturn =  kw.get("getPubmedIdForAllStructuresReturn")
getPubmedIdForAllStructuresResponse.typecode = Struct(pname=("webservices.pdb.org","getPubmedIdForAllStructuresResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="getPubmedIdForAllStructuresReturn", aname="_getPubmedIdForAllStructuresReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getPubmedIdForAllStructuresResponse, encoded="webservices.pdb.org")

class getStructureGenomicsPdbIdsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        """
getStructureGenomicsPdbIdsRequest.typecode = Struct(pname=("webservices.pdb.org","getStructureGenomicsPdbIds"), ofwhat=[], pyclass=getStructureGenomicsPdbIdsRequest, encoded="webservices.pdb.org")

class getStructureGenomicsPdbIdsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getStructureGenomicsPdbIdsReturn -- part getStructureGenomicsPdbIdsReturn
        """
        self._getStructureGenomicsPdbIdsReturn =  kw.get("getStructureGenomicsPdbIdsReturn")
getStructureGenomicsPdbIdsResponse.typecode = Struct(pname=("webservices.pdb.org","getStructureGenomicsPdbIdsResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="getStructureGenomicsPdbIdsReturn", aname="_getStructureGenomicsPdbIdsReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getStructureGenomicsPdbIdsResponse, encoded="webservices.pdb.org")

class getSwissProtIdsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        """
getSwissProtIdsRequest.typecode = Struct(pname=("webservices.pdb.org","getSwissProtIds"), ofwhat=[], pyclass=getSwissProtIdsRequest, encoded="webservices.pdb.org")

class getSwissProtIdsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getSwissProtIdsReturn -- part getSwissProtIdsReturn
        """
        self._getSwissProtIdsReturn =  kw.get("getSwissProtIdsReturn")
getSwissProtIdsResponse.typecode = Struct(pname=("webservices.pdb.org","getSwissProtIdsResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="getSwissProtIdsReturn", aname="_getSwissProtIdsReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getSwissProtIdsResponse, encoded="webservices.pdb.org")

class getGenomeDetailsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        """
getGenomeDetailsRequest.typecode = Struct(pname=("webservices.pdb.org","getGenomeDetails"), ofwhat=[], pyclass=getGenomeDetailsRequest, encoded="webservices.pdb.org")

class getGenomeDetailsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getGenomeDetailsReturn -- part getGenomeDetailsReturn
        """
        self._getGenomeDetailsReturn =  kw.get("getGenomeDetailsReturn")
getGenomeDetailsResponse.typecode = Struct(pname=("webservices.pdb.org","getGenomeDetailsResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="getGenomeDetailsReturn", aname="_getGenomeDetailsReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getGenomeDetailsResponse, encoded="webservices.pdb.org")

class getPubmedIdForStructureRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getPubmedIdForStructureRequest.typecode = Struct(pname=("webservices.pdb.org","getPubmedIdForStructure"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getPubmedIdForStructureRequest, encoded="webservices.pdb.org")

class getPubmedIdForStructureResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getPubmedIdForStructureReturn -- part getPubmedIdForStructureReturn
        """
        self._getPubmedIdForStructureReturn =  kw.get("getPubmedIdForStructureReturn")
getPubmedIdForStructureResponse.typecode = Struct(pname=("webservices.pdb.org","getPubmedIdForStructureResponse"), ofwhat=[ZSI.TC.String(pname="getPubmedIdForStructureReturn", aname="_getPubmedIdForStructureReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getPubmedIdForStructureResponse, encoded="webservices.pdb.org")

class getSequenceForStructureAndChainRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
getSequenceForStructureAndChainRequest.typecode = Struct(pname=("webservices.pdb.org","getSequenceForStructureAndChain"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getSequenceForStructureAndChainRequest, encoded="webservices.pdb.org")

class getSequenceForStructureAndChainResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getSequenceForStructureAndChainReturn -- part getSequenceForStructureAndChainReturn
        """
        self._getSequenceForStructureAndChainReturn =  kw.get("getSequenceForStructureAndChainReturn")
getSequenceForStructureAndChainResponse.typecode = Struct(pname=("webservices.pdb.org","getSequenceForStructureAndChainResponse"), ofwhat=[ZSI.TC.String(pname="getSequenceForStructureAndChainReturn", aname="_getSequenceForStructureAndChainReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getSequenceForStructureAndChainResponse, encoded="webservices.pdb.org")

class getPrimaryCitationTitleRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getPrimaryCitationTitleRequest.typecode = Struct(pname=("webservices.pdb.org","getPrimaryCitationTitle"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getPrimaryCitationTitleRequest, encoded="webservices.pdb.org")

class getPrimaryCitationTitleResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getPrimaryCitationTitleReturn -- part getPrimaryCitationTitleReturn
        """
        self._getPrimaryCitationTitleReturn =  kw.get("getPrimaryCitationTitleReturn")
getPrimaryCitationTitleResponse.typecode = Struct(pname=("webservices.pdb.org","getPrimaryCitationTitleResponse"), ofwhat=[ZSI.TC.String(pname="getPrimaryCitationTitleReturn", aname="_getPrimaryCitationTitleReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getPrimaryCitationTitleResponse, encoded="webservices.pdb.org")

class isStructureIdObsoleteRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
isStructureIdObsoleteRequest.typecode = Struct(pname=("webservices.pdb.org","isStructureIdObsolete"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=isStructureIdObsoleteRequest, encoded="webservices.pdb.org")

class isStructureIdObsoleteResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        isStructureIdObsoleteReturn -- part isStructureIdObsoleteReturn
        """
        self._isStructureIdObsoleteReturn =  kw.get("isStructureIdObsoleteReturn")
isStructureIdObsoleteResponse.typecode = Struct(pname=("webservices.pdb.org","isStructureIdObsoleteResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="isStructureIdObsoleteReturn", aname="_isStructureIdObsoleteReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=isStructureIdObsoleteResponse, encoded="webservices.pdb.org")

class getSnpInfoRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getSnpInfoRequest.typecode = Struct(pname=("webservices.pdb.org","getSnpInfo"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getSnpInfoRequest, encoded="webservices.pdb.org")

class getSnpInfoResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getSnpInfoReturn -- part getSnpInfoReturn
        """
        self._getSnpInfoReturn =  kw.get("getSnpInfoReturn")
getSnpInfoResponse.typecode = Struct(pname=("webservices.pdb.org","getSnpInfoResponse"), ofwhat=[ns0.ArrayOfSnpInfo_Def(pname="getSnpInfoReturn", aname="_getSnpInfoReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getSnpInfoResponse, encoded="webservices.pdb.org")

class getLigandInfoRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getLigandInfoRequest.typecode = Struct(pname=("webservices.pdb.org","getLigandInfo"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getLigandInfoRequest, encoded="webservices.pdb.org")

class getLigandInfoResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getLigandInfoReturn -- part getLigandInfoReturn
        """
        self._getLigandInfoReturn =  kw.get("getLigandInfoReturn")
getLigandInfoResponse.typecode = Struct(pname=("webservices.pdb.org","getLigandInfoResponse"), ofwhat=[ns0.ArrayOfLigandInfo_Def(pname="getLigandInfoReturn", aname="_getLigandInfoReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getLigandInfoResponse, encoded="webservices.pdb.org")

class smilesQueryRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        in2 -- part in2
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
        self._in2 =  kw.get("in2")
smilesQueryRequest.typecode = Struct(pname=("webservices.pdb.org","smilesQuery"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.FPfloat(pname="in2", aname="_in2", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=smilesQueryRequest, encoded="webservices.pdb.org")

class smilesQueryResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        smilesQueryReturn -- part smilesQueryReturn
        """
        self._smilesQueryReturn =  kw.get("smilesQueryReturn")
smilesQueryResponse.typecode = Struct(pname=("webservices.pdb.org","smilesQueryResponse"), ofwhat=[ns0.ArrayOfLigandInfo_Def(pname="smilesQueryReturn", aname="_smilesQueryReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=smilesQueryResponse, encoded="webservices.pdb.org")

class getSnpsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        """
getSnpsRequest.typecode = Struct(pname=("webservices.pdb.org","getSnps"), ofwhat=[], pyclass=getSnpsRequest, encoded="webservices.pdb.org")

class getSnpsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getSnpsReturn -- part getSnpsReturn
        """
        self._getSnpsReturn =  kw.get("getSnpsReturn")
getSnpsResponse.typecode = Struct(pname=("webservices.pdb.org","getSnpsResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="getSnpsReturn", aname="_getSnpsReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getSnpsResponse, encoded="webservices.pdb.org")

class getReleaseDatesRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getReleaseDatesRequest.typecode = Struct(pname=("webservices.pdb.org","getReleaseDates"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getReleaseDatesRequest, encoded="webservices.pdb.org")

class getReleaseDatesResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getReleaseDatesReturn -- part getReleaseDatesReturn
        """
        self._getReleaseDatesReturn =  kw.get("getReleaseDatesReturn")
getReleaseDatesResponse.typecode = Struct(pname=("webservices.pdb.org","getReleaseDatesResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="getReleaseDatesReturn", aname="_getReleaseDatesReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getReleaseDatesResponse, encoded="webservices.pdb.org")

class getEcNumsForStructuresRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getEcNumsForStructuresRequest.typecode = Struct(pname=("webservices.pdb.org","getEcNumsForStructures"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getEcNumsForStructuresRequest, encoded="webservices.pdb.org")

class getEcNumsForStructuresResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getEcNumsForStructuresReturn -- part getEcNumsForStructuresReturn
        """
        self._getEcNumsForStructuresReturn =  kw.get("getEcNumsForStructuresReturn")
getEcNumsForStructuresResponse.typecode = Struct(pname=("webservices.pdb.org","getEcNumsForStructuresResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="getEcNumsForStructuresReturn", aname="_getEcNumsForStructuresReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getEcNumsForStructuresResponse, encoded="webservices.pdb.org")

class getEcNumsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        """
getEcNumsRequest.typecode = Struct(pname=("webservices.pdb.org","getEcNums"), ofwhat=[], pyclass=getEcNumsRequest, encoded="webservices.pdb.org")

class getEcNumsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getEcNumsReturn -- part getEcNumsReturn
        """
        self._getEcNumsReturn =  kw.get("getEcNumsReturn")
getEcNumsResponse.typecode = Struct(pname=("webservices.pdb.org","getEcNumsResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="getEcNumsReturn", aname="_getEcNumsReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getEcNumsResponse, encoded="webservices.pdb.org")

class getCifChainRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
getCifChainRequest.typecode = Struct(pname=("webservices.pdb.org","getCifChain"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getCifChainRequest, encoded="webservices.pdb.org")

class getCifChainResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getCifChainReturn -- part getCifChainReturn
        """
        self._getCifChainReturn =  kw.get("getCifChainReturn")
getCifChainResponse.typecode = Struct(pname=("webservices.pdb.org","getCifChainResponse"), ofwhat=[ZSI.TC.String(pname="getCifChainReturn", aname="_getCifChainReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getCifChainResponse, encoded="webservices.pdb.org")

class getCifResidueRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        in2 -- part in2
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
        self._in2 =  kw.get("in2")
getCifResidueRequest.typecode = Struct(pname=("webservices.pdb.org","getCifResidue"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in2", aname="_in2", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getCifResidueRequest, encoded="webservices.pdb.org")

class getCifResidueResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getCifResidueReturn -- part getCifResidueReturn
        """
        self._getCifResidueReturn =  kw.get("getCifResidueReturn")
getCifResidueResponse.typecode = Struct(pname=("webservices.pdb.org","getCifResidueResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="getCifResidueReturn", aname="_getCifResidueReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getCifResidueResponse, encoded="webservices.pdb.org")

class getChainsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getChainsRequest.typecode = Struct(pname=("webservices.pdb.org","getChains"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getChainsRequest, encoded="webservices.pdb.org")

class getChainsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getChainsReturn -- part getChainsReturn
        """
        self._getChainsReturn =  kw.get("getChainsReturn")
getChainsResponse.typecode = Struct(pname=("webservices.pdb.org","getChainsResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="getChainsReturn", aname="_getChainsReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getChainsResponse, encoded="webservices.pdb.org")

class getCifChainsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
getCifChainsRequest.typecode = Struct(pname=("webservices.pdb.org","getCifChains"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getCifChainsRequest, encoded="webservices.pdb.org")

class getCifChainsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getCifChainsReturn -- part getCifChainsReturn
        """
        self._getCifChainsReturn =  kw.get("getCifChainsReturn")
getCifChainsResponse.typecode = Struct(pname=("webservices.pdb.org","getCifChainsResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="getCifChainsReturn", aname="_getCifChainsReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getCifChainsResponse, encoded="webservices.pdb.org")

class getChainLengthRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
getChainLengthRequest.typecode = Struct(pname=("webservices.pdb.org","getChainLength"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getChainLengthRequest, encoded="webservices.pdb.org")

class getChainLengthResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getChainLengthReturn -- part getChainLengthReturn
        """
        self._getChainLengthReturn =  kw.get("getChainLengthReturn")
getChainLengthResponse.typecode = Struct(pname=("webservices.pdb.org","getChainLengthResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="getChainLengthReturn", aname="_getChainLengthReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getChainLengthResponse, encoded="webservices.pdb.org")

class getCifChainLengthRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
getCifChainLengthRequest.typecode = Struct(pname=("webservices.pdb.org","getCifChainLength"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getCifChainLengthRequest, encoded="webservices.pdb.org")

class getCifChainLengthResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getCifChainLengthReturn -- part getCifChainLengthReturn
        """
        self._getCifChainLengthReturn =  kw.get("getCifChainLengthReturn")
getCifChainLengthResponse.typecode = Struct(pname=("webservices.pdb.org","getCifChainLengthResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="getCifChainLengthReturn", aname="_getCifChainLengthReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getCifChainLengthResponse, encoded="webservices.pdb.org")

class getKabschSanderRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
getKabschSanderRequest.typecode = Struct(pname=("webservices.pdb.org","getKabschSander"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getKabschSanderRequest, encoded="webservices.pdb.org")

class getKabschSanderResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getKabschSanderReturn -- part getKabschSanderReturn
        """
        self._getKabschSanderReturn =  kw.get("getKabschSanderReturn")
getKabschSanderResponse.typecode = Struct(pname=("webservices.pdb.org","getKabschSanderResponse"), ofwhat=[ZSI.TC.String(pname="getKabschSanderReturn", aname="_getKabschSanderReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getKabschSanderResponse, encoded="webservices.pdb.org")

class getDisorderRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
getDisorderRequest.typecode = Struct(pname=("webservices.pdb.org","getDisorder"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getDisorderRequest, encoded="webservices.pdb.org")

class getDisorderResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getDisorderReturn -- part getDisorderReturn
        """
        self._getDisorderReturn =  kw.get("getDisorderReturn")
getDisorderResponse.typecode = Struct(pname=("webservices.pdb.org","getDisorderResponse"), ofwhat=[ZSI.TC.String(pname="getDisorderReturn", aname="_getDisorderReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getDisorderResponse, encoded="webservices.pdb.org")

class getDbRefIdsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        in2 -- part in2
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
        self._in2 =  kw.get("in2")
getDbRefIdsRequest.typecode = Struct(pname=("webservices.pdb.org","getDbRefIds"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in2", aname="_in2", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getDbRefIdsRequest, encoded="webservices.pdb.org")

class getDbRefIdsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getDbRefIdsReturn -- part getDbRefIdsReturn
        """
        self._getDbRefIdsReturn =  kw.get("getDbRefIdsReturn")
getDbRefIdsResponse.typecode = Struct(pname=("webservices.pdb.org","getDbRefIdsResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="getDbRefIdsReturn", aname="_getDbRefIdsReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getDbRefIdsResponse, encoded="webservices.pdb.org")

class getPdbChainRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
getPdbChainRequest.typecode = Struct(pname=("webservices.pdb.org","getPdbChain"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getPdbChainRequest, encoded="webservices.pdb.org")

class getPdbChainResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getPdbChainReturn -- part getPdbChainReturn
        """
        self._getPdbChainReturn =  kw.get("getPdbChainReturn")
getPdbChainResponse.typecode = Struct(pname=("webservices.pdb.org","getPdbChainResponse"), ofwhat=[ZSI.TC.String(pname="getPdbChainReturn", aname="_getPdbChainReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getPdbChainResponse, encoded="webservices.pdb.org")

class runXmlQueryRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        """
        self._in0 =  kw.get("in0")
runXmlQueryRequest.typecode = Struct(pname=("webservices.pdb.org","runXmlQuery"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=runXmlQueryRequest, encoded="webservices.pdb.org")

class runXmlQueryResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        runXmlQueryReturn -- part runXmlQueryReturn
        """
        self._runXmlQueryReturn =  kw.get("runXmlQueryReturn")
runXmlQueryResponse.typecode = Struct(pname=("webservices.pdb.org","runXmlQueryResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="runXmlQueryReturn", aname="_runXmlQueryReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=runXmlQueryResponse, encoded="webservices.pdb.org")

class getCurrentPdbIdsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        """
getCurrentPdbIdsRequest.typecode = Struct(pname=("webservices.pdb.org","getCurrentPdbIds"), ofwhat=[], pyclass=getCurrentPdbIdsRequest, encoded="webservices.pdb.org")

class getCurrentPdbIdsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getCurrentPdbIdsReturn -- part getCurrentPdbIdsReturn
        """
        self._getCurrentPdbIdsReturn =  kw.get("getCurrentPdbIdsReturn")
getCurrentPdbIdsResponse.typecode = Struct(pname=("webservices.pdb.org","getCurrentPdbIdsResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="getCurrentPdbIdsReturn", aname="_getCurrentPdbIdsReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getCurrentPdbIdsResponse, encoded="webservices.pdb.org")

class getObsoletePdbIdsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        """
getObsoletePdbIdsRequest.typecode = Struct(pname=("webservices.pdb.org","getObsoletePdbIds"), ofwhat=[], pyclass=getObsoletePdbIdsRequest, encoded="webservices.pdb.org")

class getObsoletePdbIdsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getObsoletePdbIdsReturn -- part getObsoletePdbIdsReturn
        """
        self._getObsoletePdbIdsReturn =  kw.get("getObsoletePdbIdsReturn")
getObsoletePdbIdsResponse.typecode = Struct(pname=("webservices.pdb.org","getObsoletePdbIdsResponse"), ofwhat=[ns0.ArrayOf_soapenc_string_Def(pname="getObsoletePdbIdsReturn", aname="_getObsoletePdbIdsReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getObsoletePdbIdsResponse, encoded="webservices.pdb.org")

class getDomainFragmentsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        in2 -- part in2
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
        self._in2 =  kw.get("in2")
getDomainFragmentsRequest.typecode = Struct(pname=("webservices.pdb.org","getDomainFragments"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in2", aname="_in2", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getDomainFragmentsRequest, encoded="webservices.pdb.org")

class getDomainFragmentsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        getDomainFragmentsReturn -- part getDomainFragmentsReturn
        """
        self._getDomainFragmentsReturn =  kw.get("getDomainFragmentsReturn")
getDomainFragmentsResponse.typecode = Struct(pname=("webservices.pdb.org","getDomainFragmentsResponse"), ofwhat=[ns0.ArrayOfDomainFragmentWS_Def(pname="getDomainFragmentsReturn", aname="_getDomainFragmentsReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getDomainFragmentsResponse, encoded="webservices.pdb.org")

class blastQueryXmlRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
blastQueryXmlRequest.typecode = Struct(pname=("webservices.pdb.org","blastQueryXml"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.FPdouble(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=blastQueryXmlRequest, encoded="webservices.pdb.org")

class blastQueryXmlResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        blastQueryXmlReturn -- part blastQueryXmlReturn
        """
        self._blastQueryXmlReturn =  kw.get("blastQueryXmlReturn")
blastQueryXmlResponse.typecode = Struct(pname=("webservices.pdb.org","blastQueryXmlResponse"), ofwhat=[ZSI.TC.String(pname="blastQueryXmlReturn", aname="_blastQueryXmlReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=blastQueryXmlResponse, encoded="webservices.pdb.org")

class blastStructureIdQueryXmlRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        in0 -- part in0
        in1 -- part in1
        in2 -- part in2
        """
        self._in0 =  kw.get("in0")
        self._in1 =  kw.get("in1")
        self._in2 =  kw.get("in2")
blastStructureIdQueryXmlRequest.typecode = Struct(pname=("webservices.pdb.org","blastStructureIdQueryXml"), ofwhat=[ZSI.TC.String(pname="in0", aname="_in0", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="in1", aname="_in1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.FPdouble(pname="in2", aname="_in2", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=blastStructureIdQueryXmlRequest, encoded="webservices.pdb.org")

class blastStructureIdQueryXmlResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        blastStructureIdQueryXmlReturn -- part blastStructureIdQueryXmlReturn
        """
        self._blastStructureIdQueryXmlReturn =  kw.get("blastStructureIdQueryXmlReturn")
blastStructureIdQueryXmlResponse.typecode = Struct(pname=("webservices.pdb.org","blastStructureIdQueryXmlResponse"), ofwhat=[ZSI.TC.String(pname="blastStructureIdQueryXmlReturn", aname="_blastStructureIdQueryXmlReturn", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=blastStructureIdQueryXmlResponse, encoded="webservices.pdb.org")


# Service Skeletons
class PdbWebServiceService(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/pdb/services/pdbws', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_getAnnotations(self, ps, **kw):
        request = ps.Parse(getAnnotationsRequest.typecode)
        return request,getAnnotationsResponse()

    soapAction[''] = 'soap_getAnnotations'
    root[(getAnnotationsRequest.typecode.nspname,getAnnotationsRequest.typecode.pname)] = 'soap_getAnnotations'

    def soap_getEntities(self, ps, **kw):
        request = ps.Parse(getEntitiesRequest.typecode)
        return request,getEntitiesResponse()

    soapAction[''] = 'soap_getEntities'
    root[(getEntitiesRequest.typecode.nspname,getEntitiesRequest.typecode.pname)] = 'soap_getEntities'

    def soap_blastPDB(self, ps, **kw):
        request = ps.Parse(blastPDBRequest1.typecode)
        return request,blastPDBResponse1()

    soapAction[''] = 'soap_blastPDB'
    root[(blastPDBRequest1.typecode.nspname,blastPDBRequest1.typecode.pname)] = 'soap_blastPDB'

    def soap_blastPDB(self, ps, **kw):
        request = ps.Parse(blastPDBRequest1.typecode)
        return request,blastPDBResponse1()

    soapAction[''] = 'soap_blastPDB'
    root[(blastPDBRequest1.typecode.nspname,blastPDBRequest1.typecode.pname)] = 'soap_blastPDB'

    def soap_getIdStatus(self, ps, **kw):
        request = ps.Parse(getIdStatusRequest.typecode)
        return request,getIdStatusResponse()

    soapAction[''] = 'soap_getIdStatus'
    root[(getIdStatusRequest.typecode.nspname,getIdStatusRequest.typecode.pname)] = 'soap_getIdStatus'

    def soap_getAtomSite(self, ps, **kw):
        request = ps.Parse(getAtomSiteRequest.typecode)
        return request,getAtomSiteResponse()

    soapAction[''] = 'soap_getAtomSite'
    root[(getAtomSiteRequest.typecode.nspname,getAtomSiteRequest.typecode.pname)] = 'soap_getAtomSite'

    def soap_getAtomSites(self, ps, **kw):
        request = ps.Parse(getAtomSitesRequest.typecode)
        return request,getAtomSitesResponse()

    soapAction[''] = 'soap_getAtomSites'
    root[(getAtomSitesRequest.typecode.nspname,getAtomSitesRequest.typecode.pname)] = 'soap_getAtomSites'

    def soap_getFirstStructSheetRange(self, ps, **kw):
        request = ps.Parse(getFirstStructSheetRangeRequest.typecode)
        return request,getFirstStructSheetRangeResponse()

    soapAction[''] = 'soap_getFirstStructSheetRange'
    root[(getFirstStructSheetRangeRequest.typecode.nspname,getFirstStructSheetRangeRequest.typecode.pname)] = 'soap_getFirstStructSheetRange'

    def soap_getStructSheetRanges(self, ps, **kw):
        request = ps.Parse(getStructSheetRangesRequest.typecode)
        return request,getStructSheetRangesResponse()

    soapAction[''] = 'soap_getStructSheetRanges'
    root[(getStructSheetRangesRequest.typecode.nspname,getStructSheetRangesRequest.typecode.pname)] = 'soap_getStructSheetRanges'

    def soap_getFirstStructConf(self, ps, **kw):
        request = ps.Parse(getFirstStructConfRequest.typecode)
        return request,getFirstStructConfResponse()

    soapAction[''] = 'soap_getFirstStructConf'
    root[(getFirstStructConfRequest.typecode.nspname,getFirstStructConfRequest.typecode.pname)] = 'soap_getFirstStructConf'

    def soap_getStructConfs(self, ps, **kw):
        request = ps.Parse(getStructConfsRequest.typecode)
        return request,getStructConfsResponse()

    soapAction[''] = 'soap_getStructConfs'
    root[(getStructConfsRequest.typecode.nspname,getStructConfsRequest.typecode.pname)] = 'soap_getStructConfs'

    def soap_fastaStructureIdQuery(self, ps, **kw):
        request = ps.Parse(fastaStructureIdQueryRequest.typecode)
        return request,fastaStructureIdQueryResponse()

    soapAction[''] = 'soap_fastaStructureIdQuery'
    root[(fastaStructureIdQueryRequest.typecode.nspname,fastaStructureIdQueryRequest.typecode.pname)] = 'soap_fastaStructureIdQuery'

    def soap_fastaQuery(self, ps, **kw):
        request = ps.Parse(fastaQueryRequest.typecode)
        return request,fastaQueryResponse()

    soapAction[''] = 'soap_fastaQuery'
    root[(fastaQueryRequest.typecode.nspname,fastaQueryRequest.typecode.pname)] = 'soap_fastaQuery'

    def soap_homologyReductionQuery(self, ps, **kw):
        request = ps.Parse(homologyReductionQueryRequest.typecode)
        return request,homologyReductionQueryResponse()

    soapAction[''] = 'soap_homologyReductionQuery'
    root[(homologyReductionQueryRequest.typecode.nspname,homologyReductionQueryRequest.typecode.pname)] = 'soap_homologyReductionQuery'

    def soap_keywordQuery(self, ps, **kw):
        request = ps.Parse(keywordQueryRequest.typecode)
        return request,keywordQueryResponse()

    soapAction[''] = 'soap_keywordQuery'
    root[(keywordQueryRequest.typecode.nspname,keywordQueryRequest.typecode.pname)] = 'soap_keywordQuery'

    def soap_pubmedAbstractQuery(self, ps, **kw):
        request = ps.Parse(pubmedAbstractQueryRequest.typecode)
        return request,pubmedAbstractQueryResponse()

    soapAction[''] = 'soap_pubmedAbstractQuery'
    root[(pubmedAbstractQueryRequest.typecode.nspname,pubmedAbstractQueryRequest.typecode.pname)] = 'soap_pubmedAbstractQuery'

    def soap_getSpaceGroupForStructure(self, ps, **kw):
        request = ps.Parse(getSpaceGroupForStructureRequest.typecode)
        return request,getSpaceGroupForStructureResponse()

    soapAction[''] = 'soap_getSpaceGroupForStructure'
    root[(getSpaceGroupForStructureRequest.typecode.nspname,getSpaceGroupForStructureRequest.typecode.pname)] = 'soap_getSpaceGroupForStructure'

    def soap_getPubmedIdForAllStructures(self, ps, **kw):
        request = ps.Parse(getPubmedIdForAllStructuresRequest.typecode)
        return request,getPubmedIdForAllStructuresResponse()

    soapAction[''] = 'soap_getPubmedIdForAllStructures'
    root[(getPubmedIdForAllStructuresRequest.typecode.nspname,getPubmedIdForAllStructuresRequest.typecode.pname)] = 'soap_getPubmedIdForAllStructures'

    def soap_getStructureGenomicsPdbIds(self, ps, **kw):
        request = ps.Parse(getStructureGenomicsPdbIdsRequest.typecode)
        return request,getStructureGenomicsPdbIdsResponse()

    soapAction[''] = 'soap_getStructureGenomicsPdbIds'
    root[(getStructureGenomicsPdbIdsRequest.typecode.nspname,getStructureGenomicsPdbIdsRequest.typecode.pname)] = 'soap_getStructureGenomicsPdbIds'

    def soap_getSwissProtIds(self, ps, **kw):
        request = ps.Parse(getSwissProtIdsRequest.typecode)
        return request,getSwissProtIdsResponse()

    soapAction[''] = 'soap_getSwissProtIds'
    root[(getSwissProtIdsRequest.typecode.nspname,getSwissProtIdsRequest.typecode.pname)] = 'soap_getSwissProtIds'

    def soap_getGenomeDetails(self, ps, **kw):
        request = ps.Parse(getGenomeDetailsRequest.typecode)
        return request,getGenomeDetailsResponse()

    soapAction[''] = 'soap_getGenomeDetails'
    root[(getGenomeDetailsRequest.typecode.nspname,getGenomeDetailsRequest.typecode.pname)] = 'soap_getGenomeDetails'

    def soap_getPubmedIdForStructure(self, ps, **kw):
        request = ps.Parse(getPubmedIdForStructureRequest.typecode)
        return request,getPubmedIdForStructureResponse()

    soapAction[''] = 'soap_getPubmedIdForStructure'
    root[(getPubmedIdForStructureRequest.typecode.nspname,getPubmedIdForStructureRequest.typecode.pname)] = 'soap_getPubmedIdForStructure'

    def soap_getSequenceForStructureAndChain(self, ps, **kw):
        request = ps.Parse(getSequenceForStructureAndChainRequest.typecode)
        return request,getSequenceForStructureAndChainResponse()

    soapAction[''] = 'soap_getSequenceForStructureAndChain'
    root[(getSequenceForStructureAndChainRequest.typecode.nspname,getSequenceForStructureAndChainRequest.typecode.pname)] = 'soap_getSequenceForStructureAndChain'

    def soap_getPrimaryCitationTitle(self, ps, **kw):
        request = ps.Parse(getPrimaryCitationTitleRequest.typecode)
        return request,getPrimaryCitationTitleResponse()

    soapAction[''] = 'soap_getPrimaryCitationTitle'
    root[(getPrimaryCitationTitleRequest.typecode.nspname,getPrimaryCitationTitleRequest.typecode.pname)] = 'soap_getPrimaryCitationTitle'

    def soap_isStructureIdObsolete(self, ps, **kw):
        request = ps.Parse(isStructureIdObsoleteRequest.typecode)
        return request,isStructureIdObsoleteResponse()

    soapAction[''] = 'soap_isStructureIdObsolete'
    root[(isStructureIdObsoleteRequest.typecode.nspname,isStructureIdObsoleteRequest.typecode.pname)] = 'soap_isStructureIdObsolete'

    def soap_getSnpInfo(self, ps, **kw):
        request = ps.Parse(getSnpInfoRequest.typecode)
        return request,getSnpInfoResponse()

    soapAction[''] = 'soap_getSnpInfo'
    root[(getSnpInfoRequest.typecode.nspname,getSnpInfoRequest.typecode.pname)] = 'soap_getSnpInfo'

    def soap_getLigandInfo(self, ps, **kw):
        request = ps.Parse(getLigandInfoRequest.typecode)
        return request,getLigandInfoResponse()

    soapAction[''] = 'soap_getLigandInfo'
    root[(getLigandInfoRequest.typecode.nspname,getLigandInfoRequest.typecode.pname)] = 'soap_getLigandInfo'

    def soap_smilesQuery(self, ps, **kw):
        request = ps.Parse(smilesQueryRequest.typecode)
        return request,smilesQueryResponse()

    soapAction[''] = 'soap_smilesQuery'
    root[(smilesQueryRequest.typecode.nspname,smilesQueryRequest.typecode.pname)] = 'soap_smilesQuery'

    def soap_getSnps(self, ps, **kw):
        request = ps.Parse(getSnpsRequest.typecode)
        return request,getSnpsResponse()

    soapAction[''] = 'soap_getSnps'
    root[(getSnpsRequest.typecode.nspname,getSnpsRequest.typecode.pname)] = 'soap_getSnps'

    def soap_getReleaseDates(self, ps, **kw):
        request = ps.Parse(getReleaseDatesRequest.typecode)
        return request,getReleaseDatesResponse()

    soapAction[''] = 'soap_getReleaseDates'
    root[(getReleaseDatesRequest.typecode.nspname,getReleaseDatesRequest.typecode.pname)] = 'soap_getReleaseDates'

    def soap_getEcNumsForStructures(self, ps, **kw):
        request = ps.Parse(getEcNumsForStructuresRequest.typecode)
        return request,getEcNumsForStructuresResponse()

    soapAction[''] = 'soap_getEcNumsForStructures'
    root[(getEcNumsForStructuresRequest.typecode.nspname,getEcNumsForStructuresRequest.typecode.pname)] = 'soap_getEcNumsForStructures'

    def soap_getEcNums(self, ps, **kw):
        request = ps.Parse(getEcNumsRequest.typecode)
        return request,getEcNumsResponse()

    soapAction[''] = 'soap_getEcNums'
    root[(getEcNumsRequest.typecode.nspname,getEcNumsRequest.typecode.pname)] = 'soap_getEcNums'

    def soap_getCifChain(self, ps, **kw):
        request = ps.Parse(getCifChainRequest.typecode)
        return request,getCifChainResponse()

    soapAction[''] = 'soap_getCifChain'
    root[(getCifChainRequest.typecode.nspname,getCifChainRequest.typecode.pname)] = 'soap_getCifChain'

    def soap_getCifResidue(self, ps, **kw):
        request = ps.Parse(getCifResidueRequest.typecode)
        return request,getCifResidueResponse()

    soapAction[''] = 'soap_getCifResidue'
    root[(getCifResidueRequest.typecode.nspname,getCifResidueRequest.typecode.pname)] = 'soap_getCifResidue'

    def soap_getChains(self, ps, **kw):
        request = ps.Parse(getChainsRequest.typecode)
        return request,getChainsResponse()

    soapAction[''] = 'soap_getChains'
    root[(getChainsRequest.typecode.nspname,getChainsRequest.typecode.pname)] = 'soap_getChains'

    def soap_getCifChains(self, ps, **kw):
        request = ps.Parse(getCifChainsRequest.typecode)
        return request,getCifChainsResponse()

    soapAction[''] = 'soap_getCifChains'
    root[(getCifChainsRequest.typecode.nspname,getCifChainsRequest.typecode.pname)] = 'soap_getCifChains'

    def soap_getChainLength(self, ps, **kw):
        request = ps.Parse(getChainLengthRequest.typecode)
        return request,getChainLengthResponse()

    soapAction[''] = 'soap_getChainLength'
    root[(getChainLengthRequest.typecode.nspname,getChainLengthRequest.typecode.pname)] = 'soap_getChainLength'

    def soap_getCifChainLength(self, ps, **kw):
        request = ps.Parse(getCifChainLengthRequest.typecode)
        return request,getCifChainLengthResponse()

    soapAction[''] = 'soap_getCifChainLength'
    root[(getCifChainLengthRequest.typecode.nspname,getCifChainLengthRequest.typecode.pname)] = 'soap_getCifChainLength'

    def soap_getKabschSander(self, ps, **kw):
        request = ps.Parse(getKabschSanderRequest.typecode)
        return request,getKabschSanderResponse()

    soapAction[''] = 'soap_getKabschSander'
    root[(getKabschSanderRequest.typecode.nspname,getKabschSanderRequest.typecode.pname)] = 'soap_getKabschSander'

    def soap_getDisorder(self, ps, **kw):
        request = ps.Parse(getDisorderRequest.typecode)
        return request,getDisorderResponse()

    soapAction[''] = 'soap_getDisorder'
    root[(getDisorderRequest.typecode.nspname,getDisorderRequest.typecode.pname)] = 'soap_getDisorder'

    def soap_getDbRefIds(self, ps, **kw):
        request = ps.Parse(getDbRefIdsRequest.typecode)
        return request,getDbRefIdsResponse()

    soapAction[''] = 'soap_getDbRefIds'
    root[(getDbRefIdsRequest.typecode.nspname,getDbRefIdsRequest.typecode.pname)] = 'soap_getDbRefIds'

    def soap_getPdbChain(self, ps, **kw):
        request = ps.Parse(getPdbChainRequest.typecode)
        return request,getPdbChainResponse()

    soapAction[''] = 'soap_getPdbChain'
    root[(getPdbChainRequest.typecode.nspname,getPdbChainRequest.typecode.pname)] = 'soap_getPdbChain'

    def soap_runXmlQuery(self, ps, **kw):
        request = ps.Parse(runXmlQueryRequest.typecode)
        return request,runXmlQueryResponse()

    soapAction[''] = 'soap_runXmlQuery'
    root[(runXmlQueryRequest.typecode.nspname,runXmlQueryRequest.typecode.pname)] = 'soap_runXmlQuery'

    def soap_getCurrentPdbIds(self, ps, **kw):
        request = ps.Parse(getCurrentPdbIdsRequest.typecode)
        return request,getCurrentPdbIdsResponse()

    soapAction[''] = 'soap_getCurrentPdbIds'
    root[(getCurrentPdbIdsRequest.typecode.nspname,getCurrentPdbIdsRequest.typecode.pname)] = 'soap_getCurrentPdbIds'

    def soap_getObsoletePdbIds(self, ps, **kw):
        request = ps.Parse(getObsoletePdbIdsRequest.typecode)
        return request,getObsoletePdbIdsResponse()

    soapAction[''] = 'soap_getObsoletePdbIds'
    root[(getObsoletePdbIdsRequest.typecode.nspname,getObsoletePdbIdsRequest.typecode.pname)] = 'soap_getObsoletePdbIds'

    def soap_getDomainFragments(self, ps, **kw):
        request = ps.Parse(getDomainFragmentsRequest.typecode)
        return request,getDomainFragmentsResponse()

    soapAction[''] = 'soap_getDomainFragments'
    root[(getDomainFragmentsRequest.typecode.nspname,getDomainFragmentsRequest.typecode.pname)] = 'soap_getDomainFragments'

    def soap_blastQueryXml(self, ps, **kw):
        request = ps.Parse(blastQueryXmlRequest.typecode)
        return request,blastQueryXmlResponse()

    soapAction[''] = 'soap_blastQueryXml'
    root[(blastQueryXmlRequest.typecode.nspname,blastQueryXmlRequest.typecode.pname)] = 'soap_blastQueryXml'

    def soap_blastStructureIdQueryXml(self, ps, **kw):
        request = ps.Parse(blastStructureIdQueryXmlRequest.typecode)
        return request,blastStructureIdQueryXmlResponse()

    soapAction[''] = 'soap_blastStructureIdQueryXml'
    root[(blastStructureIdQueryXmlRequest.typecode.nspname,blastStructureIdQueryXmlRequest.typecode.pname)] = 'soap_blastStructureIdQueryXml'

