>P1;1HZX_A
bovine rhodopsin
MNGTEGPNFYVPFSNKTGVVRSPFEAPQYYLAEPWQFSMLAAYMFLLIMLGFPINFLTLY
VTVQHKKLRTPLNYILLNLAVADL-FMVFGGFTTTLYTSLHGYFVFGPTGCNLEGFFATL
GGEIALWSLVVLAIERYVVVCKPMS-NFRFGENHAIMGVAFTWVMALACAAPPLVGWSRY
IPEGMQCSCGIDYYTPHEETNNESFVIYMFVVHFIIPLIVIFFCYGQLVFTV----KEAA
AQQQESATTQ-------------KAEKEVTRMVIIMVIAFLICWLPYAGVAFYIFTHQGS
DFGPI------FMTIPAFFAKTSAVYNPVIYIMMNKQFRNCMVTTL-----CCGKNPLGD
DEASTTVSKTETSQVAPA*

>P1;2J4Y_A
a rhodopsin-stabilizing mutant
--GTEGPNFYVPFSNKTGVVRSPFEAPQYYLAEPWQFSMLAAYMFLLIMLGFPINFLTLY
VTVQHKKLRTPLNYILLNLAVADL-FMVFGGFTTTLYTSLHGYFVFGPTGCNLEGFFATL
GGEIALWSLVVLAIERYVVVCKPMS-NFRFGENHAIMGVAFTWVMALACAAPPLVGWSRY
IPEGMQCSCGIDYYTPHEETNNESFVIYMFVVHFIIPLIVIFFCYGQLVFTV----KEAA
AQQQESATTQ-------------KAEKEVTRMVIIMVIAFLICWLPYAGVAFYIFTHQGS
CFGPI------FMTIPAFFAXTSAVYNPVIYIMMNKQFRNCMVTTL-----CCGKNPLGD
DEASTTVSKTETSQVAPA*

>P1;2Z73_A
squid rhodopsin
-----------------------------------------------------------Y
LFTKTKSLQTPANMFIINLAFSDFTFSLVNGFPLMTISCFLKKWIFGFAACKVYGFIGGI
FGFMSIMTMAMISIDRYNVIGRPMAASKKMSHRRAFIMIIFVWLWSVLWAIGPIFGWGAY
TLEGVLCNCSFDYIS--RDSTTRSNILCMFILGFFGPILIIFFCYFNIVMSVSNHEKEMA
A-----MAKRLNAKELRKAQAGANAEMRLAKISIVIVSQFLLSWSPYAVVALL------A
QFGPLEWVTPYAAQLPVMFAKASAIHNPMIYSVSHPKFREAISQTFPWVLTCC-------
------------------*
