>P1;1kao
structureX:1kao:   1 : : 167 : :rap2a:Homo sapiens:1.70:18.6
-----MREYKVVVLGSGGVGKSALTVQFVTGTFIEKYD-PTI-EDFYRK
EIEVDSSPSVLEILDTAGTEQFASMRDLYIKNGQGFILVYSLVNQQSFQD
IKP-MRDQIIRVKRYEKVPVILVGNKVDLES------E------REVSS
SEGRALAEEW-----GCPFMETSAKS--------KTMVDELFAEIVRQMN
YA-----------*
>P1;1guaa
structureX:1gua:   1 :A: 167 :A:rap1a:Homo sapiens:2.00:22.0
-----MREYKLVVLGSGGVGKSALTVQFVQGIFVDEYD-PTI-EDSYRK
QVEVDCQQCMLEILDTAGTEQFTAMRDLYMKNGQGFALVYSITAQSTFND
LQD-LREQILRVKDTEDVPMILVGNKCDLED------E------RVVGK
EQGQNLARQWC----NCAFLESSAKS--------KINVNEIFYDLVRQIN
R------------*
>P1;5p21
structureX:5p21:   1 : : 166 : :Harvey-ras p21:Homo sapiens: 1.40:19.60
-----MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYD-PTI-EDSYRK
QVVIDGETCLLDILDTAGQEEYSAMRDQYMRTGEGFLCVFAINNTKSFED
IHQ-YREQIKRVKDSDDVPMVLVGNKCDL-A------A------RTVES
RQAQDLARSY-----GIPYIETSAKT--------RQGVEDAFYTLVREIR
QH-----------*
>P1;1mh1
structureX:1mh1:   1A: : 181 : :rac1:Homo sapiens:1.38:17.5
--GS-PQAIKCVVVGDGAVGKTCLLISYTTNAFPGEYI-PTV-FDNYSA
NVMVDGKPVNLGLWDTAGQEDYDRLRPLSYPQTDVSLICFSLVSPASFEN
VRAKWYPEVRHHCP--NTPIILVGTKLDLRDDKDTIEKLKEKKLTPITY
PQGLAMAKEIG----AVKYLECSALT--------QRGLKTVFDEAIRAVL
CPPP---------*
>P1;1ftn
structureX:1ftn:   4 : : 180 : :rhoA (H12):Homo sapiens:2.10:18.6
------IRKKLVIVGDGACGKTCLLIVNSKDQFPEVYV-PTV-FENYVA
DIEVDGKQVELALWDTAGQEDYDRLRPLSYPDTDVILMCFSIDSPDSLEN
IPEKWTPEVKHFCP--NVPIILVGNKKDLRNDEHTRRELAKMKQEPVKP
EEGRDMANRIG----AFGYMECSAKT--------KDGVREVFEMATRAAL
Q------------*
>P1;1etu
structureX:1etu:   5 : : 200 : :elongation factor Tu (domain I):Escherichia coli: 2.90:18.00
FERT-KPHVNVGTIGHVDHGKTTLTAAITTV-LAKTYG-ITINTSHVEY
DTP----TRHYAHVDCPGHADYVKNMITGAAQMDGAILVVAATDG-PMPQ
TRE-HILLGRQVG---VPYIIVFLNKCDMVDD---------EELLELVE
MEVRELLSQYDFPGDDTPIVRGSALKALEGDAEWEAKILELAGFLDSYIP
-------------*
>P1;1a4ra
structureX:1a4r:   1 :A: 190 :A:g25k GTP-binding protein, placental isoform:Homo sapiens:2.5:22.8
-----MQTIKCVVVGDVAVGKTCLLISYTTNKFPSEYV-PTV-FDNYAV
TVMIGGEPYTLGLFDTAGQEDYDRLRPLSYPQTDVFLVCFSVVSPSSFEN
VKEKWVPEITHHCP--KTPFLLVGTQIDLRDDPSTIEKLAKNKQKPITP
ETAEKLARDLK----AVKYVECSALT--------QKGLKNVFDEAILAAL
EPPEPKKSRRCVL*
>P1;1zbda
structureX:1zbd:  16 :A: 192 :A:ras-related protein rab-3a:Rattus norvegicus:2.60:23.3
-SH-FDY-FKILIIGNSSVGKTSFLFRYADDSFTPAFV-STVGIDFKVK
TIYRNDKRIKLQIWDTAGLERYRTITTAYYRGA-GFIL-YDITNEESFNA
VQD-WSTQIKTYSW-DNAQVLLVGNKCD-ED------------ERVVSS
ERGRQLADHLG-----FEFFEASAKD--------NINVKQTFERLVDVIC
EKSESL------D*
