CategoryOrder = [
	"General Controls",
	"Viewing Controls",
	"Depiction",
	"Structure Analysis",
	"Structure Comparison",
	'Sequence',
	"Surface/Binding Analysis",
	"Structure Editing",
	"Amber",
	"MD/Ensemble Analysis",
	"Higher-Order Structure",
	"Volume Data",
	"Demos",
	"Movement",
	"Utilities",
]

ToolOrder = {
	"Demos": [
		"COX Inhibitors Demo",
		"Hormone-Receptor Complex Demo",
		"Demo Editor",
		"About Demos",
	],
	"Depiction": [
		"Color Secondary Structure",
		"Rainbow",
		"PipesAndPlanks",
		"Nucleotides",
		"Ribbon Style Editor",
		"Render by Attribute",
		"Surface Capping",
		"Per-Model Clipping",
		'Color Zone',
		"MainChain",
		"PseudoBond Reader",
	],
	"General Controls": [
		"Command Line",
		"Model Panel",
		"PseudoBond Panel",
		"Keyboard Shortcuts",
		"Task Panel",
		"IDLE",
	],
	"Higher-Order Structure": [
		"Multiscale Models",
		"Unit Cell",
		'Crystal Contacts',
		'Small-Angle X-Ray Profile',
		"Scale Bar",
		"Icosahedron Surface",
		'Flatten Icosahedron',
	],
	"MD/Ensemble Analysis": [
		"MD Movie",
		"Ensemble Cluster",
		"Ensemble Match",
		"Tile Structures",
	],
	"Movement": [
		"Rotation",
		"Undo Move",
		"Redo Move",
		'Movement Mouse Mode',
		"Constrained Move",
		'Transform Molecule Coordinates',
	],
	"Sequence": [
		"Sequence",
		"Multalign Viewer",
		"Match -> Align",
		"Blast Protein"
	],
	"Structure Analysis": [
		"FindHBond",
		"Find Clashes/Contacts",
		"Sequence",
		"Distances",
		"Angles/Torsions",
		"Axes/Planes",
		"Thermal Ellipsoids",
		"Adjust Torsions",
		"Render by Attribute",
		"Define Attribute",
		"Attribute Calculator",
		"Add Charge",
		"ResProp",
	],
	"Structure Comparison": [
		"MatchMaker",
		"Multalign Viewer",
		"Match -> Align",
		"Morph Conformations",
		"Ensemble Cluster",
		"Ensemble Match",
		"Tile Structures",
		"Minrms Plot",
	],
	"Structure Editing": [
		"AddH",
		"Add Charge",
		"Dock Prep",
		"Rotamers",
		"Adjust Torsions",
		"Build Structure",
                "Movement Mouse Mode",
		"Minimize Structure",
		"Add Ions",
		"Solvate",
		"Write DMS",
		"Model Loops"
	],
	"Surface/Binding Analysis": [
		"FindHBond",
		"Find Clashes/Contacts",
		"Electrostatic Surface Coloring",
		"Coulombic Surface Coloring",
		"Surface Capping",
		"Surface Zone",
		"ViewDock",
		"Dock Prep",
		"Measure Volume and Area",
		"Area/Volume from Web",
		"Measure and Color Blobs",
		'Intersurf',
		"Surfnet - Interface",
		"Surfnet - Selected Atoms",
		"DelPhiController",
		"HearDock",
	],
	"Utilities": [
		"Reply Log",
		"2D Labels",
		"Movie Recorder",
		"Color Key",
		"Structure Diagram",
		"Browser Configuration",
		"Benchmark",
		"Color Editor",
		"2D Texture",
		"ReadStdin",
		"Debug Graphics Driver",
	],
	"Viewing Controls": [
		"Side View",
		"Camera",
		"Effects",
		"Lighting",
		"Shininess",
	],
	"Volume Data": [
		'Volume Viewer',
		'Fit in Map',
		'Surface Color',
		'Color Zone',
		'Morph Map',
		'Volume Tracer',
		'Volume Filter',
		'Hide Dust',
		'Volume Eraser',
		'Measure Volume and Area',
		'Measure and Color Blobs',
		'Volume Mean, SD, RMS',
		'Values at Atom Positions',
		'Volume Series',
		'Phantom Force Feedback',
		'Volume Menu on Menubar',
	],
}
